spring.datasource.name: platform
spring.datasource.jdbcUrl: jdbc:dm://192.168.88.128:5235
spring.datasource.username: FLOWABLE6_5
spring.datasource.password: FLOWABLE6_5
spring.datasource.driverClassName: dm.jdbc.driver.DmDriver
spring.datasource.initialSize: 5
spring.datasource.minIdle: 5
spring.datasource.maxActive: 20
spring.datasource.maxWait: 60000
spring.datasource.dev.poolPreparedStatements: true
spring.datasource.dev.maxPoolPreparedStatementPerConnectionSize: 20
spring.datasource.dev.useGlobalDataSourceStat: true
spring.datasource.dev.logType: slf4j
spring.datasource.dev.timeBetweenEvictionRunsMillis: 60000
spring.datasource.dev.minEvictableIdleTimeMillis: 300000
spring.datasource.dev.validationQuery: SELECT 1
spring.datasource.dev.testWhileIdle: true
spring.datasource.dev.testOnBorrow: false
spring.datasource.dev.testOnReturn: true
spring.datasource.dev.idleTimeout: 60000
spring.datasource.dev.connectionTimeout: 60000
spring.datasource.dev.validationTimeout: 3000
spring.datasource.dev.loginTimeout: 5

#flowable.common.app.idm-url: http://localhost:8080/flowable-idm
#flowable.common.app.idm-admin.user: admin
#flowable.common.app.idm-admin.password: test