spring.http.encoding.force: true
spring.jackson.time-zone: GMT+8
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.aop.proxy-target-class: true
spring.servlet.multipart.max-request-size: 900MB
spring.servlet.multipart.max-file-size: 900MB

spring.profiles.active: dev
server:
  port: 8888
  servlet:
    context-path: /flowable-modeler
